### 50_startupdata ###
startupdata <- read.csv(file.choose())
attach(startupdata)
View(startupdata)
startupdata$State <- as.numeric(startupdata$State)
str(startupdata)
View(startupdata)
is.na(startupdata)
sum(is.na(startupdata))
summary(startupdata)
plot(Profit,R.D.Spend)
plot(Profit,Administration)
plot(Profit,Marketing.Spend)
plot(Profit,State)
pairs(startupdata)
cor(startupdata)
cor(R.D.Spend,Profit)
model.startupdata <- lm(Profit~R.D.Spend+Administration+Marketing.Spend+State)
summary(model.startupdata)
model.admin <- lm(Profit~Administration)
summary(model.admin)
model.market <- lm(Profit~Marketing.Spend)
summary(model.market)
model.state <- lm(Profit~State)
summary(model.state)
summary(lm(Profit~Administration+Marketing.Spend+State))
library(car)
plot(model.startupdata)
qqPlot(model.startupdata,id.n=3)
influence.measures(model.startupdata)
influenceIndexPlot(model.startupdata,id.n=3)
influencePlot(model.startupdata,id.n=3)
model.startupdata1 <- lm(Profit~.,data = startupdata[-50,])
summary(model.startupdata1)
summary(lm(Profit~.,data = startupdata[-c(46,50),]))
vif(model.startupdata)
vifprofit <- lm(Profit~R.D.Spend+Administration+Marketing.Spend+State)
vifspend <- lm(R.D.Spend~Profit+Administration+Marketing.Spend+State)
vifadmin <- lm(Administration~ R.D.Spend+Profit+Marketing.Spend+State)
vifmarket <- lm(Marketing.Spend~ R.D.Spend+Administration+Profit+State)
vifstate <- lm(State~R.D.Spend+Administration+Marketing.Spend+Profit)
summary(vifprofit)
summary(vifspend)
summary(vifadmin)
summary(vifmarket)
summary(vifstate)
library(car)
avPlots(model.startupdata)
library(MASS)
stepAIC(model.startupdata)
model.final <- lm(formula = Profit ~ R.D.Spend + Marketing.Spend,data = startupdata[c(-50,-46),])
summary(model.final)
avPlots(model.final,id.n=3)
vif(model.final)



### computer data ###
library(car)
library(psych)
computerdata <- read.csv(file.choose())
attach(computerdata)
View(computerdata)
summary(computerdata)
str(computerdata)
computerdata$cd <- as.integer(computerdata$cd)
computerdata$multi <- as.integer(computerdata$multi)
computerdata$premium <- as.integer(computerdata$premium)
str(computerdata)
summary(computerdata)
pairs.panels(computerdata,col="red")
cor(computerdata)
model.compdata <- lm(price~.,data = computerdata)
summary(model.compdata)
avPlots(model.compdata)
qqPlot(model.compdata,id.n=3)
stepAIC(model.compdata)
vif(model.compdata)
model.final <- lm(price~.,data = computerdata[-c(1701,1441),])
summary(model.final)
avPlots(model.final,id.n=3)
vif(model.final)




### Toyota Corolla data ###
toyotacorolla <- read.csv(file.choose())
toyota <- toyotacorolla[c("Price","Age_08_04","KM","HP","cc","Doors","Gears","Quarterly_Tax","Weight")]
View(toyota)
attach(toyota)
summary(toyota)
cor(toyota)
library(car)
library(psych)
pairs.panels(toyota)
plot(toyota)
model.toyota <- lm(Price~.,data = toyota)
summary(model.toyota)
model.cc <- lm(Price~cc,data = toyota)
summary(model.cc)
model.doors <- lm(Price~Doors,data = toyota)
summary(model.doors)
summary(lm(Price~cc+Doors,data = toyota))
avPlots(model.toyota,id.n=3)
vif(model.toyota)
summary(lm(Price~.,data = toyota[c(-222,-602,-961),]))
stepAIC(model.toyota)
summary(lm(formula = Price ~ Age_08_04 + KM + HP + Gears + Quarterly_Tax + Weight, data = toyota))
model.final <- lm(Price~.,data = toyota[c(-222,-602,-961),])
summary(model.final)
